source "http://rubygems.org"
gem "aruba", "~> 0.3.6"
gem "rake"
gem "rails", ">= 3.0.7"
gem "thin"
gem "shoulda"
gem "sqlite3"
gem "factory_girl"
gem "diesel"
gem "cucumber-rails", "~> 0.4.1"
gem "capybara"
gem "factory_girl_rails"
gem "rspec-rails", "~> 2.6.0"
gem "launchy"
gem "mocha"
